Генерирует разметку для объявлений на основе шаблона
htmlacademy-javascript/2127963-keksobooking-27 pull request #5
Opened 2022-11-07 12:45 UTC by ElveeC

2022-11-07 13:53 UTC, pavel-nyukalo requested changes

2022-11-07 13:53 UTC, pavel-nyukalo commented on js/main.js
> +import {createAdvertisments} from './create-advertisments.js';
`createAdvertisments` используются теперь в `popup.js` и сюда их можно не импортировать (и вызов удалить)

2022-11-07 13:53 UTC, pavel-nyukalo commented on js/popup.js
> +  }
Точно ли нам нужно удалять свойство объекта, а не элемент из разметки? (`author.avatar.remove();`)

По заданию:
> Например, отсутствует описание. В этом случае соответствующий блок в карточке скрывается.

Под "соответствующий блок" тут подразумевается именно элемент в разметке

2022-11-07 13:53 UTC, pavel-nyukalo commented on js/popup.js
> +
Этих данных тоже может не быть, и в таком случае тоже надо будет скрывать блоки.

Тут предлагаю так:
1. Найти все необходимые элементы в начале функции
2. И далее уже с ними взаимодействовать и проверять каждое свойство (в целом пока можно на `if/else`, но если будет время можно подумать в сторону написания вспомогательной функции, куда мы просто передадим поле, проверим есть ли оно, если есть выведем, если нет удалим элемент из разметки)

2022-11-07 15:13 UTC, ElveeC commented on js/popup.js
> +  }
Т.е. нужно создать переменную для cardElement.querySelector('.popup__avatar') и ее удалять?

2022-11-08 11:03 UTC, pavel-nyukalo approved these changes

2022-11-08 11:03 UTC, merged